# Basic Algebra 

`
f = 2 * x + y
`

In [2]:
import torch
import numpy as np

In [15]:
x_np = np.array([[1,2,3],[4,5,6]])
y_np = np.array([[7,8,9],[10,11,12]])

In [16]:
2 * x_np + y_np

array([[ 9, 12, 15],
       [18, 21, 24]])

In [69]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])

In [63]:
2 * x + y

tensor([[ 9, 12, 15],
        [18, 21, 24]])

In [70]:
y.add_(x * 2)

tensor([[ 9, 12, 15],
        [18, 21, 24]])

# Convert tensors and numpy

In [26]:
y

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [27]:
x_np

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
torch.from_numpy(x_np) + y # convert to tensor to add tensor data type

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [71]:
torch.from_numpy(x_np).numpy() # numpy to tensor to numpy

array([[1, 2, 3],
       [4, 5, 6]])

# Reshaping dimension

In [51]:
x.view(-1)

tensor([1, 2, 3, 4, 5, 6])

In [41]:
x_np.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [54]:
x.transpose(0,1) # also work with transpose_

tensor([[1, 4],
        [2, 5],
        [3, 6]])

# Verify Tensor 

In [12]:
x = [np.random.randint(100) for i in range(5)]

In [13]:
torch.is_tensor(x)

False

In [14]:
torch.is_storage(x)

False

In [31]:
torch.is_tensor(torch.tensor(x))

True

In [32]:
torch.is_storage(torch.tensor(x))

False

In [34]:
len(x)

5

In [33]:
torch.numel(torch.tensor(x))

5